config/routes.rb
Instadium::Application.routes.draw do
  namespace :admin do
    get 'dashboard/index'
    root :to => "results#index"
    resources :results
    resources :trivia_configs
    resources :trivia
    match "delete_image", :to => "trivia_configs#delete_image", via: [:get, :post]
  end




  root :to => "home#index"
  match "answers", :to => "home#answers", via: [:get, :post]
  get "home/text", :to => "home#text"
  devise_for :users, :controllers => { :confirmations => "confirmations", :registrations => "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  mount Rapidfire::Engine => "/survey"

  mount API => '/'

end

app/models/result.rb
class Result < ActiveRecord::Base
  def self.answer_statistic
    total = Result.count.to_f
    q1, q5, q10 = 0, 0, 0
    Result.all.each do |result|
     q1 += 1 if result.right_answers.include?("1") 
     q5 += 1 if result.right_answers.include?("5")
     q10 += 1 if result.right_answers.include?("10")
    end
    

    return [(q1/total)*100, (q5/total)*100, (q10/total)*100] 
  end
end

app/controllers/admin/results_controller.rb
class Admin::ResultsController < ApplicationController
  layout 'admin'
  before_filter :authenticate_user!
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to admin_result_path(@result), notice: 'Result was successfully created.' }
        format.json { render action: 'show', status: :created, location: @result }
      else
        format.html { render action: 'new' }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to admin_result_path(@result), notice: 'Result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to admin_results_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:ip, :url, :right_answers, :started_at, :finished_at, :score, 
                                     :user_code, :originator_code, :source)
    end
end

app/views/admin/results/_form.html.slim
= simple_form_for(@result) do |f|
  = f.error_notification

  .form-inputs
    = f.input :ip
    = f.input :url
    = f.input :right_answers
    = f.input :started_at
    = f.input :finished_at
    = f.input :score

  .form-actions
    = f.button :submit

app/views/admin/results/edit.html.slim
h1 Editing result

== render 'form'

= link_to 'Show', @result
'|
= link_to 'Back', results_path

app/views/admin/results/index.html.slim
.panel.panel-success
  .panel-heading
    | Results
  .panel-body
    table.table.table-striped
      thead
        tr
          th Ip
          th Id
          th Originator
          th Source
          th Url
          th Right answers
          /th Started at
          /th Finished at
          th Score
          th
          th

      tbody
        - @results.each do |result|
          tr
            td = result.ip
            td = result.user_code
            td = result.originator_code
            td = result.source
            td = result.url
            td = result.right_answers
            /td = result.started_at
            /td = result.finished_at
            td = result.score
            td = link_to 'Show', admin_result_path(result) , :class=>"btn btn-default btn-sm"
            /td = link_to 'Edit', edit_result_path(result)
            td = link_to 'Destroy', admin_result_path(result), data: {:confirm => 'Are you sure?'}, 
              :method => :delete, :class=>"btn btn-danger btn-sm"

    br

    /= link_to 'New Result', new_result_path, :class=>"btn "

app/views/admin/results/new.html.slim
h1 New result

== render 'form'

= link_to 'Back', results_path

app/views/admin/results/show.html.slim
.panel.panel-success
  .panel-heading
    | Result info:
  .panel-body
    p#notice = notice

    p
      strong Ip: 
      = @result.ip
    p
      strong User code: 
      = @result.user_code
    p
      strong Originator: 
      = @result.originator_code
    p
      strong Source: 
      = @result.source
    p
      strong Right answers: 
      = @result.right_answers
    p
      strong Started at: 
      = @result.started_at
    p
      strong Finished at: 
      = @result.finished_at
    p
      strong Score: 
      = @result.score

    /= link_to 'Edit', edit_result_path(@result)
    /'|
  .panel-footer
    = link_to 'Back', admin_results_path, :class=>"btn btn-default btn-sm"