config/routes.rb
Instadium::Application.routes.draw do
  namespace :admin do
    get 'dashboard/index'
    root :to => "results#index"
    resources :results
    resources :trivia_configs
    resources :trivia
    match "delete_image", :to => "trivia_configs#delete_image", via: [:get, :post]
  end




  root :to => "home#index"
  match "answers", :to => "home#answers", via: [:get, :post]
  get "home/text", :to => "home#text"
  devise_for :users, :controllers => { :confirmations => "confirmations", :registrations => "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  mount Rapidfire::Engine => "/survey"

  mount API => '/'

end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
- if user_signed_in?
  li= link_to 'Edit account', edit_user_registration_path
  li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  li= link_to 'Sign in', new_user_session_path
  li= link_to 'Sign up', new_user_registration_path
- if user_signed_in?
  li= link_to 'Users', users_path

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'InStadium Trivia'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Below you’ll find 10 questions designed to test your knowledge of sports and pop culture.'}"
    link href='//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'
    = favicon_link_tag "favicon.png"
    /== stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" /
    link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css" rel="stylesheet" /

    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js" 
    == csrf_meta_tags
    
    /script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"
    /script type="text/javascript" src="//flesler-plugins.googlecode.com/files/jquery.scrollTo-1.4.2-min.js"
    /script type="text/javascript" src="//flesler-plugins.googlecode.com/files/jquery.localscroll-1.2.7-min.js"
    /link rel="image_src" href=image_path('IS_grey_logo.jpg')
  body style="padding-top: 60px;"
    .navbar.navbar-inverse.navbar-fixed-top role="navigation" 
      .container
        .navbar-header
          button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button" 
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="/admin/results"  InStadium Admin
        .navbar-collapse.collapse
          ul.nav.navbar-nav
            li class=('open' if request.env['PATH_INFO'].include? "results")
              a href="#{admin_results_path}"  Results
            li class=('open' if (request.env['PATH_INFO'].include?("trivia") && !request.env['PATH_INFO'].include?("trivia_config")))
              a href="#{admin_trivia_path}"  Trivia
            li class=('open' if request.env['PATH_INFO'].include? "trivia_configs")
              a href="#{admin_trivia_configs_path}"  Trivia Config
          ul.nav.navbar-nav.navbar-right
            - if user_signed_in?  
              li.divider-vertical
                a href=(edit_user_registration_path(:method => :get)) 
                  = current_user.email
              li.divider-vertical
                a data-method="delete" href=destroy_user_session_path 
                  | Logout
    /! /.nav-collapse
    /== render 'layouts/messages'
    .container
      .panel.panel-info
        .panel-heading
          | Statistic
        .panel-body.bg-info
          .col-md-4
            strong 
              | Total Uniq Players: 
              = Result.uniq.pluck(:user_code).size
            br  
            strong
              | Total Played Games: 
              = Result.count
          .col-md-4
            - [1,5,10].each_with_index do |number,index|
              strong
                | Right answers for question #{number}:   
                = number_to_percentage(Result.answer_statistic[index], precision: 0)
                br
          .col-md-4
            strong
             | 
          
      .row
        .col-md-12
          == yield

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'InStadium Trivia'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Below you’ll find 10 questions designed to test your knowledge of sports and pop culture.'}"
    link href='//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'
    = favicon_link_tag "favicon.png"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
    script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"
    script type="text/javascript" src="//flesler-plugins.googlecode.com/files/jquery.scrollTo-1.4.2-min.js"
    script type="text/javascript" src="//flesler-plugins.googlecode.com/files/jquery.localscroll-1.2.7-min.js"
    link rel="image_src" href=image_path('IS_grey_logo.jpg')
  body
    == render 'layouts/messages'
    == yield

app/views/layouts/swagger.html.slim
doctype html
html  xmlns="http://www.w3.org/1999/xhtml" lang=I18n.locale.to_s xml:lang=(I18n.locale.to_s ) 
  head
    title Swagger UI

    = javascript_include_tag :swagger_ui
    = stylesheet_link_tag :swagger_ui, :media => :all
    = csrf_meta_tags

    css:
      .swagger-ui-wrap {
         max-width: 80%;
         min-width: 960px;
         margin-left: auto;
         margin-right: auto;
       }
    
    javascript:
       $(function(){
         $.ajaxPrefilter(function(o, options){
           options.headers = { 'X-CSRF-Token': '#{form_authenticity_token.to_s}' }
         });
       });

       $(function () {
         window.swaggerUi = new SwaggerUi({
           discoveryUrl: "https://#{request.host}:#{request.port}/api/swagger_doc.json",
           apiKey:"",
           dom_id:"swagger-ui-container",
           supportHeaderParams: false,
           supportedSubmitMethods: ['get', 'post', 'put']
         });
         window.swaggerUi.load();
       });

  body
    #header
      .swagger-ui-wrap
        h1#logo Encore API
        form#api_selector
          .input
            input#input_baseUrl  placeholder= "https://#{request.host}/api" name= "baseUrl" type= "text"  
          .input
            input#input_apiKey  placeholder= "api_key" name= "apiKey" type= "text"  
          .input
            a#explore  href= "#"
              | Explore

    #message-bar.swagger-ui-wrap &nbsp;
    #swagger-ui-container.swagger-ui-wrap